<?php

use Illuminate\Database\Seeder;
use App\Models\PropertyValue;

class VehicleBrandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Alfa Romeo";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Ferrari";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Dodge";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Subaru";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Toyota";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Volkswagen";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Volvo";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Audi";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "BMW";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Buick";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Cadillac";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Chevrolet";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Chrysler";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Nissan";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Ford";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Hyundai";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Infiniti";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Lexus";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Mercury";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Mazda";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Oldsmobile";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Plymouth";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Pontiac";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Rolls Royce";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Eagle";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Lincoln";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Mercedes Benz";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "GMC";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Saab";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Honda";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Saturn";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Mitsubishi";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Isuzu";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Jeep";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "AM General";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Geo";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Suzuki";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Land Rover";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Acura";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Jaguar";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Porsche";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Kia";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Lamborghini";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Panoz Auto Development";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Maserati";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Saleen";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Aston Martin";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Federal Coach";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Lotus";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Bentley";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Daewoo";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Roush Performance";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Bertone";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "TVR Engineering Ltd";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Morgan";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "MINI";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Yugo";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "BMW Alpina";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Renault";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Scion";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Maybach";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Peugeot";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Spyker";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Hummer";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Bugatti";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Pininfarina";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Shelby";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Smart";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Tecstar";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Volga Associated Automobile";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Mahindra";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Fiat";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Sterling";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "McLaren Automotive";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Ram";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Fisker";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Tesla";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "BYD";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Pagani";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Genesis";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Karma";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Koenigsegg";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Aurora Cars Ltd";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "RUF Automobile";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Dacia";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Daihatsu";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Merkur";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "JBA Motorcars";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "General Motors";
		$value->save();
		$value = new PropertyValue();
		$value->property_id = 2;
		$value->possible_value = "Citroen";
		$value->save();
    }
}
